export default {
  meta: "META SZCZYRK",
  meta3: "META III SZCZYRK",
  auto: "WARSZTAT",
  biuro: "BIURO",
  hotel: "HOTEL",
  jaworzno: "JAWORZNO",
  kfc: "KFC",
  partyzantow: "PARTYZANTÓW",
  pilsudzkiego: "PIŁSUDZKIEGO",
  rybaczowka: "RYBACZÓWKA",
  stadnina: "STADNINA",
  szkola: "SZKOŁA",
  vaco: "VACO",
};
